name = "create_serv"
author = "RustyNova"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
refresh = 1

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a665fd47b7c05326d9e1cf0d020758090444af8b8f5acc0cb7f2908af70c7542"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.203"

[options]
acceptable-game-versions = ["1.12.1"]
