name = "create_serv"
author = "RustyNova"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3737ce6a54b272565e3dd54757ac44bdad5c12d84a7a56c243b7944419d1f011"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.203"

[options]
acceptable-game-versions = ["1.12.1"]
