name = "create_serv"
author = "RustyNova"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "39a8767063ba806f5a35e95a140c2b83108171bb4bdb137eb289e005db21a9c6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.203"

[options]
acceptable-game-versions = ["1.12.1"]
